yarnPath: .yarn/releases/yarn-2.1.1.cjs

packageExtensions:
  '@apollographql/apollo-tools@*':
    dependencies:
      'graphql': '*'

  # Might need to add this as well
  ws@*:
    dependencies:
      'bufferutil': '*'
      'utf-8-validate': '*'
