steps:
  - name: node
    entrypoint: yarn
    args: ['install']
  - name: node
    entrypoint: yarn
    args: ['run', 'create-env']
    env:
      - 'CLIENT_TOKEN_SECRET=${_CLIENT_TOKEN_SECRET}'
      - 'MONGODB_CONNECTION_URL=${_MONGODB_CONNECTION_URL}'
      - 'SERVICE_URL=${_SERVICE_URL}'
      - 'DEV_PORT=${_DEV_PORT}'
      - 'ALLOWED_ORIGINS=${_ALLOWED_ORIGINS}'
      - 'CAS_VALIDATE_URL=${_CAS_VALIDATE_URL}'
      - 'COLLEGES=${_COLLEGES}'
      - 'MAJORS=${_MAJORS}'
      - 'MINORS=${_MINORS}'
      - 'NODE_ENV=${_NODE_ENV}'
      - 'TOKEN_EXPIRE_TIME=${_TOKEN_EXPIRE_TIME}'
      - 'MAX_REPORTS=${_MAX_REPORTS}'
      - 'AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID}'
      - 'AWS_SECRET=${_AWS_SECRET}'
      - 'BUCKET=${_BUCKET}'
      - 'REGION=${_REGION}'
      - 'NODE_ENV=${_NODE_ENV}'
  - name: node
    entrypoint: yarn
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'src/app.yaml', '--version=2']
