import 'dotenv/config';

const CLIENT_TOKEN_SECRET = process.env.CLIENT_TOKEN_SECRET;
const MONGODB_CONNECTION_URL = process.env.MONGODB_CONNECTION_URL;

export {
	CLIENT_TOKEN_SECRET,
	MONGODB_CONNECTION_URL,
};
